name: Auto Merge Dependency Updates

on:
  - pull_request
  - pull_request_review

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
